// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9CnT5BShTmDBITJNPL6fzwlWOW2UD7-E',
    appId: '1:1086164950250:web:b2c90c11361c13ceb24b93',
    messagingSenderId: '1086164950250',
    projectId: 'fitperfect-6de75',
    authDomain: 'fitperfect-6de75.firebaseapp.com',
    storageBucket: 'fitperfect-6de75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRmi2YvLk-InOvUPXusJBeLrkwUcfKN8Y',
    appId: '1:1086164950250:android:762c889f6c23c3e3b24b93',
    messagingSenderId: '1086164950250',
    projectId: 'fitperfect-6de75',
    storageBucket: 'fitperfect-6de75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKIikUM8V6i0Gts6Ug0kYiwaKB4A-wuSI',
    appId: '1:1086164950250:ios:0e304ff53e8cc87ab24b93',
    messagingSenderId: '1086164950250',
    projectId: 'fitperfect-6de75',
    storageBucket: 'fitperfect-6de75.firebasestorage.app',
    iosBundleId: 'com.example.feasibilityTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKIikUM8V6i0Gts6Ug0kYiwaKB4A-wuSI',
    appId: '1:1086164950250:ios:0e304ff53e8cc87ab24b93',
    messagingSenderId: '1086164950250',
    projectId: 'fitperfect-6de75',
    storageBucket: 'fitperfect-6de75.firebasestorage.app',
    iosBundleId: 'com.example.feasibilityTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9CnT5BShTmDBITJNPL6fzwlWOW2UD7-E',
    appId: '1:1086164950250:web:9edf2d0abd619944b24b93',
    messagingSenderId: '1086164950250',
    projectId: 'fitperfect-6de75',
    authDomain: 'fitperfect-6de75.firebaseapp.com',
    storageBucket: 'fitperfect-6de75.firebasestorage.app',
  );
}
